'\" t
.\"     Title: tang-show-keys
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 07/12/2018
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "TANG\-SHOW\-KEYS" "1" "07/12/2018" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
tang-show-keys \- Output signing key thumbprints
.SH "SYNOPSIS"
.sp
\fBtang\-show\-keys\fR [<PORT>]
.SH "DESCRIPTION"
.sp
It is sometimes necessary to manually verify that a client has received the expected Tang advertisement\&.
.sp
The client will usually show the thumbprints of the signing keys in the advertisement it got, and this tool will show the thumbprints of the signing keys used by the Tang server on localhost\&. If these two sets of thumbprints agree, the client has the right advertisement and it is safe to let the client use it\&.
.sp
<PORT> is the port that the Tang server is listening on on localhost\&. It defaults to 80\&.
.SH "AUTHOR"
.sp
Marius Vollmer <marius\&.vollmer@redhat\&.com>
.SH "SEE ALSO"
.sp
\fBtang\fR(8)
