#!/bin/bash
# vim: set tabstop=8 shiftwidth=4 softtabstop=4 expandtab smarttab colorcolumn=80:
#
# Copyright (c) 2018 Red Hat, Inc.
# Author: Marius Vollmer <marius.vollmer@redhat.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

set -e

if [ $# -gt 1 ]; then
    echo "Usage: $0 [<port>]" >&2
    exit 1
fi

port=${1-80}

adv=$(curl -sSf localhost:$port/adv)

echo $adv \
    | jose fmt -j- -g payload -y -o- \
    | jose jwk use -i- -r -u verify -o- \
    | jose jwk thp -i-
